@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow

together {
    Class PersonListPanel
    Class EventListPanel
    Class StatisticsPanel
    Class PersonDetailPanel
    Class OnboardingPanel
}

together {
    Class PersonCard
    Class EventCard
}

together {
    Class HelpWindow
    Class ResultDisplay
    Class CommandBox
    Class StatusBarFooter
}
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
UiManager -right-> Logic
MainWindow *-down-> "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" PersonListPanel
MainWindow *-down-> "1" EventListPanel
MainWindow *-down-> "1" StatisticsPanel
MainWindow *-down-> "1" PersonDetailPanel
MainWindow *-down-> "1" OnboardingPanel
MainWindow *-down-> "1" StatusBarFooter
MainWindow --> "0..1" HelpWindow
MainWindow -right-> Logic

PersonListPanel -down-> "*" PersonCard
EventListPanel -down-> "*" EventCard

MainWindow -left-|> UiPart
ResultDisplay --|> UiPart
CommandBox --|> UiPart
HelpWindow --|> UiPart
StatusBarFooter --|> UiPart
PersonListPanel --|> UiPart
EventListPanel --|> UiPart
StatisticsPanel --|> UiPart
PersonDetailPanel --|> UiPart
OnboardingPanel --|> UiPart
PersonCard --|> UiPart
EventCard --|> UiPart

PersonCard ..> Model
EventCard ..> Model
PersonDetailPanel ..> Model

MainWindow -[hidden]-|> UiPart
@enduml
